name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/releases/${{ github.run_number }}'

      - name: Login to Yandex Cloud Container Registry
        run: |
          echo ${{ secrets.yandex_oauth }} | docker login \
            --username oauth \
            --password-stdin \
            cr.yandex


      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crp6flpsq42sl65e0kb8
          CR_REPOSITORY: app
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY --all-tags

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.run_number }}

      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog
        run: |
          echo "## ${github.run_number}\n ${github.event.commits}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md