name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CR_REGISTRY: crp6flpsq42sl65e0kb8
      CR_REPOSITORY: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze commits
        run: |
          COMMITS=$(git log --oneline --no-merges | grep -B 999 "tag:" | head -n -1)
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo ${{ env.COMMITS }}
          git log --oneline --no-merges

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Login to Yandex Cloud Container Registry
        run: |
          echo ${{ secrets.yandex_oauth }} | docker login \
            --username oauth \
            --password-stdin \
            cr.yandex


      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crp6flpsq42sl65e0kb8
          CR_REPOSITORY: app
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:${IMAGE_TAG}_latest .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY --all-tags

      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NUMBER: ${{ github.run_number }}
          AUTHOR: ${{ github.actor }}
          DOCKER_IMAGE: cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:${{ github.run_number }}


      - name: Update changelog
        run: |
          printf "## ${{ github.run_number }}\n ${{ env.COMMITS }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push


      - name: Create branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/releases/${{ github.run_number }}'

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.run_number }}